// <auto-generated />
using CM20314.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CM20314.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231222183007_AddBuildings")]
    partial class AddBuildings
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("CM20314.Models.Database.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Entity");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Entity");
                });

            modelBuilder.Entity("CM20314.Models.Database.Container", b =>
                {
                    b.HasBaseType("CM20314.Models.Database.Entity");

                    b.HasDiscriminator().HasValue("Container");
                });

            modelBuilder.Entity("CM20314.Models.Database.Coordinate", b =>
                {
                    b.HasBaseType("CM20314.Models.Database.Entity");

                    b.HasDiscriminator().HasValue("Coordinate");
                });

            modelBuilder.Entity("CM20314.Models.Database.Node", b =>
                {
                    b.HasBaseType("CM20314.Models.Database.Entity");

                    b.HasDiscriminator().HasValue("Node");
                });

            modelBuilder.Entity("CM20314.Models.Database.NodeArc", b =>
                {
                    b.HasBaseType("CM20314.Models.Database.Entity");

                    b.HasDiscriminator().HasValue("NodeArc");
                });

            modelBuilder.Entity("CM20314.Models.Database.Building", b =>
                {
                    b.HasBaseType("CM20314.Models.Database.Container");

                    b.HasDiscriminator().HasValue("Building");
                });
#pragma warning restore 612, 618
        }
    }
}
