// <auto-generated />
using CM20314.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CM20314.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240220214314_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("CM20314.Models.Database.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Entity");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Entity");
                });

            modelBuilder.Entity("CM20314.Models.Database.Container", b =>
                {
                    b.HasBaseType("CM20314.Models.Database.Entity");

                    b.Property<string>("LongName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PolylineIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Container");
                });

            modelBuilder.Entity("CM20314.Models.Database.Coordinate", b =>
                {
                    b.HasBaseType("CM20314.Models.Database.Entity");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasDiscriminator().HasValue("Coordinate");
                });

            modelBuilder.Entity("CM20314.Models.Database.Node", b =>
                {
                    b.HasBaseType("CM20314.Models.Database.Entity");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CoordinateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Floor")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Node");
                });

            modelBuilder.Entity("CM20314.Models.Database.NodeArc", b =>
                {
                    b.HasBaseType("CM20314.Models.Database.Entity");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<int>("Node1Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Node2Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodeArcType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequiresUsageRequest")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("StepFree")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("NodeArc");
                });

            modelBuilder.Entity("CM20314.Models.Database.Building", b =>
                {
                    b.HasBaseType("CM20314.Models.Database.Container");

                    b.Property<string>("Floors")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Building");
                });

            modelBuilder.Entity("CM20314.Models.Database.Floor", b =>
                {
                    b.HasBaseType("CM20314.Models.Database.Container");

                    b.HasDiscriminator().HasValue("Floor");
                });

            modelBuilder.Entity("CM20314.Models.Database.Room", b =>
                {
                    b.HasBaseType("CM20314.Models.Database.Container");

                    b.Property<int>("BuildingId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Room_BuildingId");

                    b.Property<bool>("ExcludeFromRooms")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrimaryFloor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecondaryFloor")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Room");
                });
#pragma warning restore 612, 618
        }
    }
}
